# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test-r-code

jobs:
  test-r-code:
  
    runs-on: ${{ matrix.os }}

    name: Testing R code on ${{ matrix.os }} (r ${{ matrix.r }})

    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macOS-latest'] #, 'windows-2019' ]
        r: [ 'devel' ] #, 'release', 'oldrel-1', '4.3.1', '4.3.0', '4.2.3', '4.2.2', '4.2.1', '4.2.0', '4.1.3', '4.1.2', '4.1.1', '4.1.0', '4.0.5', '3.6.1' ]

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}
    
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      
      - name: "Configure java pour ubuntu et macos"
        if: runner.os != 'Windows'
        run: sudo R CMD javareconf
      
      # - name: "Set language parameters"
      #   run: |
      #     echo "LC_ALL=fr_FR.UTF-8" >> /etc/environment
      #     echo "fr_FR.UTF-8 UTF-8" >> /etc/locale.gen
      #     echo "LANG=fr_FR.UTF-8" > /etc/locale.conf
      #     locale-gen fr_FR.UTF-8
      
      - name: "Install R packages"
        run: install.packages("remotes");remotes::install_github("InseeFrLab/rjdworkspace")
        shell: Rscript {0}
        
      - name: test-r-code
        run: Rscript ./R/tempdir_bug.R
