# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:
  push:
   branches: [main, master]
  #pull_request:
  #  branches: [main, master]

name: test-r-code

jobs:
  test-r-code:
  
    runs-on: ${{ matrix.os }}

    name: Testing R code on ${{ matrix.os }} (r ${{ matrix.r }})

    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macOS-latest']
        r: [ 'release' ] #,'devel', 'release', 'oldrel-1', '4.3.1', '4.3.0',  '4.2.3',  '4.2.2', '4.2.1', '4.2.0', '4.1.3', '4.1.2', '4.1.1', '4.1.0', '4.0.5', '3.6.1' ]

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-tinytex@v2
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}
    
      - name: test-r-code
        run: Rscript ./R/main.R
