# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on: workflow_dispatch

name: Commands

jobs:
  style:
    name: style
    runs-on: ubuntu-latest
    outputs:
      has_changed: ${{ steps.check_changes.outputs.changed }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: create
        run: |
          touch news.txt
          git add -N news.txt
        
      # Check if there are any changes
      - name: Check for changes
        id: check_changes
        run: |
          git diff --name-only
          git_diff=$(git diff --name-only)
          #echo "has_changed=$(git diff --name-only)" >> $GITHUB_OUTPUT
          echo "has_changed=bon)" >> $GITHUB_OUTPUT
          #echo "Voici les modifs :\n $git_diff"
          #echo "${{ steps.check_changes.outputs.changed }}"
          
      - name: print
        run: echo "$GITHUB_OUTPUT"
      
      - name: Commit changes
        if: ${{ steps.check_changes.outputs.changed != '' }}
        run: |
          echo "il y a des changements"
      
      - name: Commit no changes
        if: ${{ steps.check_changes.outputs.changed == '' }}
        run: |
          echo "il y a pas des changements"
